# Imagen base de Node.js
FROM node:18-slim

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos necesarios para instalar dependencias
COPY package.json package-lock.json ./
RUN npm install --silent

# Copiar todo el código fuente al contenedor
COPY . .

# Exponer el puerto que usa el servidor
EXPOSE 3001

# Comando para iniciar la aplicación
CMD ["node", "app.js"]
